GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "YoYo",
    "author": "yoyo",
    "url": "www.mlemlem.com"
}
###
DELETE http://localhost:3001/api/blogs/649d45f0d966c29d4711e113
###
PUT http://localhost:3001/api/blogs/649d7380fa1703e9a2b8df3a
Content-Type: application/json

{
    "title": "Rocky",
    "author": "Rocky",
    "url": "www.meomeo.com",
    "likes": 100
}